name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 30
    name: ${{ matrix.name }} (${{ matrix.os }}, ${{ matrix.python-version }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-11.0, windows-2019]
        python-version: [3.8, 3.9, "3.10"]
        tox_env: [py-orange-released]
        experimental: [false]
        name: [Released]
        include:
          - os: windows-2019
            python-version: 3.8
            tox_env: py-orange-released
            experimental: true
            name: Windows10

          - os: windows-2019
            python-version: 3.8
            tox_env: py-orange-oldest
            experimental: false
            name: Oldest
          - os: macos-11.0
            python-version: 3.8
            tox_env: py-orange-oldest
            name: Oldest
            experimental: false
          - os: ubuntu-18.04
            python-version: 3.8
            tox_env: py-orange-oldest
            name: Oldest
            experimental: false

          - os: windows-2019
            python-version: "3.10"
            tox_env: py-orange-latest
            experimental: false
            name: Latest
          - os: macos-11.0
            python-version: "3.10"
            tox_env: py-orange-latest
            experimental: false
            name: Latest
          - os: ubuntu-18.04
            python-version: "3.10"
            tox_env: py-orange-latest
            experimental: false
            name: Latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox==3.8.3 # https://github.com/tox-dev/tox/issues/1550#issuecomment-725405553
          python -m pip install --upgrade tox-pip-version

      - name: Set environment variable
        # this step sets QT_QPA_PLATFORM env which is mandatory on Linux and
        # it is skipped on Windows since it produces SEGFAULT when WebView used
        if: runner.os != 'Windows'
        run: |
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV

      - name: Test with Tox
        run: |
          tox -e ${{ matrix.tox_env }}

      - name: Upload code coverage
        if: |
          matrix.python-version == '3.8' &&  
          matrix.os == 'ubuntu-18.04' && 
          matrix.tox_env == 'py-orange-released'
        run: |
          pip install codecov
          codecov
